version: '3.8'

services:
  mail_api:
    build: .
    image: mail_service_api:latest
    networks:
      - mail_internal
      - sharednet
    volumes:
      - ./src:/var/www/html/src
      - ./templates:/var/www/html/templates
      - ./logs:/var/www/html/logs
    environment:
      - DB_HOST=mail_db
      - DB_NAME=mail_service
      - DB_USER=mail_user
      - DB_PASSWORD=secure_mail_pass_2024
      - REDIS_HOST=mail_redis
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - INTER_SERVICE_SECRET=mail_user_service_secret_key_2024
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      update_config:
        parallelism: 1
        delay: 10s
    depends_on:
      - mail_db
      - mail_redis

  mail_nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    networks:
      - mail_internal
      - sharednet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - mail_api

  mail_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_mail_pass_2024
      MYSQL_DATABASE: mail_service
      MYSQL_USER: mail_user
      MYSQL_PASSWORD: secure_mail_pass_2024
    volumes:
      - mail_db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - mail_internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "3307:3306"

  mail_redis:
    image: redis:7-alpine
    volumes:
      - mail_redis_data:/data
    networks:
      - mail_internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: redis-server --appendonly yes

  mail_worker:
    build: .
    image: mail_service_api:latest
    command: php /var/www/html/src/workers/mail_queue_worker.php
    networks:
      - mail_internal
    volumes:
      - ./src:/var/www/html/src
      - ./templates:/var/www/html/templates
      - ./logs:/var/www/html/logs
    environment:
      - DB_HOST=mail_db
      - DB_NAME=mail_service
      - DB_USER=mail_user
      - DB_PASSWORD=secure_mail_pass_2024
      - REDIS_HOST=mail_redis
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    depends_on:
      - mail_db
      - mail_redis

  mail_admin:
    build: 
      context: .
      dockerfile: Dockerfile.admin
    image: mail_service_admin:latest
    networks:
      - mail_internal
    ports:
      - "8082:80"
    volumes:
      - ./admin:/var/www/html
    environment:
      - API_URL=http://mail_nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mail_db_data:
  mail_redis_data:

networks:
  mail_internal:
    driver: overlay
    attachable: true
  sharednet:
    external: true
